language: python
python: "3.7"
dist: bionic
#before_install: pip3 install --upgrade pip && pip3 install -r requirements/dev.txt
install:
  - pip3 install .
#  - pip3 install codecov
#script: pytest --cov-report=xml --cov=onepassword_local_search
script: /bin/true
deploy:
  skip_cleanup: true
  provider: pypi
  user: mickaelperrin
  distributions: "bdist bdist_wheel"
  password:
    secure: "GRAaZnlXcT3ubS5TsrMV+PX8p7Kafi9H7AHGmY3UkB6DsG/+JrNLxJ3qpMJEc7fMTqbkYqK3u1tT8PhKXi3slNp0bucwFHSXx/YrzNqEvVfET7vpgYkRCSCEYbeUh5cTEHCuT7N0gOfI8ThMdxOGww6S8nPB/kLKhBnF06coJZDbyEymD9JcLrJ61QTLpukt7fvYpHTR7q2j7LBTHDX26TnOAvxmc30NITKO6FHjhPHDfOwoCO+51y0aftCaFguchTwxvqroEJHdiUw5/JF2VQR7rN87VAxHq76cRH37XqvkgFYsgz6ZCE/Sb2yn6pOhoML+itrSpXrwuB3nBHyzQa91O5q96gdKsrvS6tpWzeg0WCl737lLE8mBp7gPlgsMjM08ulXd4AJwRZjNqe7g9rLtc8ca9CjAS5w9EngEc7/tKrGmha5ZpqQ07OLNpu7dnA0WCI8iGPRYjkCu1n/VQsSaU+dgQom24MB9c4OuMP6qocypdo7hjm0eLHvAeSZBZPiyFF4y5wi0tm2wmocHj1xg3dDqJlMTmIA5o9pZGvWUL0etypYYUfKT6trTMXySmX92vYszWarrQeKVThvY08TgjDHk6s9KeFG7V38ij0fVMSRv+8TH5hyFDxlKyQoL+2gdvK9vEnmdK19ypGhvrQLeLlnEkEAZNc51R1hLmAU="
  skip_existing: true
  on:
    branch: master
    tags: true
#after_success:
#  - codecov
